### PR TITLE
Fix bugs of SQL JOIN and column generation

### LINKED ISSUE #215: Resource cannot have two relations to the same resource if it has another relational resource
Example schema:
```
schemas:

- id: gakko
  description: Gakko
  singular: gakko
  plural: gakkos
  title: Gakko
  prefix: /v1.0
  schema:
    properties:
      id:
        description: The ID of Gakko
        format: uuid
        title: ID
        type: string
      name:
        description: Name
        title: Name
        type: string

- id: kodomo
  description: Kodomo
  singular: kodomo
  plural: kodomos
  title: Kodomo
  prefix: /v1.0
  schema:
    properties:
      id:
        description: The ID of Kodomo
        format: uuid
        title: ID
        type: string
      gakko_id:
        description: Gakko
        title: Gakko
        type: string
        relation: gakko
        relation_property: gakko

- id: oya
  description: Oya
  singular: oya
  plural: oyas
  title: Oya
  prefix: /v1.0
  schema:
    properties:
      id:
        description: The ID of Oya
        format: uuid
        title: ID
        type: string
      otoko_id:
        description: Otoko no ko
        title: Otoko
        type: string
        relation: kodomo
        relation_property: otoko_kodomo
      onna_id:
        description: Onna no ko
        title: Onna
        type: string
        relation: kodomo
        relation_property: onna_kodomo
```

Example initial values.
```
gakkos:
- id: gakko1
  name: Gakko 1
kodomos:
- id: otoko_id
  gakko_id: gakko1
- id: onna_id
  gakko_id: gakko1
oyas:
- id: oya_id
  otoko_id: otoko_id
  onna_id: onna_id
```

In this setting, if you want to get the list of oyas like `curl http://localhost:9091/v1.0/oyas`, following errors show:
```
18:13:49.638 gohan.db.sql DEBUG  Executing SQL query 'SELECT oyas.`id` as `oyas__id`, oyas.`otoko_id` as `oyas__otoko_id`, otoko_kodomo.`id` as `otoko_kodomo__id`, otoko_kodomo.`gakko_id` as `otoko_kodomo__gakko_id`, gakko.`id` as `gakko__id`, gakko.`name` as `gakko__name`, oyas.`onna_id` as `oyas__onna_id`, onna_kodomo.`id` as `onna_kodomo__id`, onna_kodomo.`gakko_id` as `onna_kodomo__gakko_id`, gakko.`id` as `gakko__id`, gakko.`name` as `gakko__name` FROM `oyas` LEFT JOIN `kodomos` as `otoko_kodomo` on `oyas`.`otoko_id` = `otoko_kodomo`.id LEFT JOIN `gakkos` as `gakko` on `otoko_kodomo`.`gakko_id` = `gakko`.id LEFT JOIN `kodomos` as `onna_kodomo` on `oyas`.`onna_id` = `onna_kodomo`.id LEFT JOIN `gakkos` as `gakko` on `onna_kodomo`.`gakko_id` = `gakko`.id ORDER BY oyas.`id` asc'
18:13:49.638 gohan.server.middleware ERROR  Error 1066: Not unique table/alias: 'gakko'
```

The root cause is gohan produced two same 'gakko' aliases.

### PR DESCRIPTION
**Pull request by morrisson**
If some resource has two or more relation properties to the same
resource which has some other relation properties, SQL join
generation can generate ambiguous alias. To avoid this problem,
table and column name should be generalized in the recursive manner.

fixes #215

### CODE REVIEW

File: db/sql/sql.go [hunk 1]
```diff
@@ -505,14 +505,24 @@ func makeColumn(tableName string, property schema.Property) string {
 }
 
 // MakeColumns generates an array that has Gohan style colmun names
-func MakeColumns(s *schema.Schema, tableName string, join bool) []string {
+func MakeColumns(s *schema.Schema, tableName string, join bool, aliasTableName string) []string {
 	var cols []string
 	manager := schema.GetManager()
 	for _, property := range s.Properties {
-		cols = append(cols, makeColumn(tableName, property)+" as "+quote(makeColumnID(tableName, property)))
+        if aliasTableName != "" {
```
Comment (nati) [inline db/sql/sql.go]: how about
if aliasTableName == "" {
  aliasTableName = tableName;
}

File: server/server_test.go [hunk 2]
```diff
@@ -237,6 +240,32 @@ var _ = Describe("Server package test", func() {
 		})
 	})
 
+    Describe("TwoSameResourceRelations", func ()  {
+        It("should work", func ()  {
+			By("creating 2 gakko")
```
Comment (nati) [inline server/server_test.go]: could you use english words in test code?

File: db/sql/sql.go [hunk 3]
```diff
@@ -528,17 +538,28 @@ func makeStateColumns(s *schema.Schema) (cols []string) {
 	return cols
 }
 
-func makeJoin(s *schema.Schema, tableName string, q sq.SelectBuilder) sq.SelectBuilder {
+func makeJoin(s *schema.Schema, tableName string, q sq.SelectBuilder, aliasRelationPropertyPrefix string, aliasTableName string) sq.SelectBuilder {
```
Comment (nati) [inline db/sql/sql.go]: I'm not sure we need aliasTableName..
How about just pass newAliasTableName as tableName and omit l543-545

**Comment by nati** [comment]
also rebase needed

File: db/sql/sql.go (hunk 1 above)
Comment (morrisson) [inline db/sql/sql.go]: aliasTableName is used for if evaluation below, so this value should not be changed here.

File: db/sql/sql.go (hunk 3 above)
Comment (morrisson) [inline db/sql/sql.go]: Actually, aliasTableName is important when top level resource has two children with the same resources which has two or more depth relations. Without newAliasTableName, current test passes because child resource of top level resource in my test schema has only one depth relation. In the next patch, I will modify test schema to check if this aliasTableName is needed.

File: server/server_test.go (hunk 2 above)
Comment (morrisson) [inline server/server_test.go]: Ok.

File: db/sql/sql.go (hunk 1 above)
Comment (nati) [inline db/sql/sql.go]: I believe we can do this always.

 newAliasTableName = aliasTableName + "__" + property.RelationProperty

File: db/sql/sql.go (hunk 3 above)
Comment (nati) [inline db/sql/sql.go]: Why not do 

newAliasTableName = aliasTableName + "__" + property.RelationProperty

for always? if we do this, we can simplify logic.

**Comment by morrisson** [comment]
Thanks for your comment. I can make simpler logic.

File: db/sql/sql.go [hunk 4]
```diff
@@ -505,14 +505,18 @@ func makeColumn(tableName string, property schema.Property) string {
...
-func MakeColumns(s *schema.Schema, tableName string, join bool) []string {
+func MakeColumns(s *schema.Schema, tableName string, join bool, aliasTableName string) []string {
 	var cols []string
 	manager := schema.GetManager()
 	for _, property := range s.Properties {
-		cols = append(cols, makeColumn(tableName, property)+" as "+quote(makeColumnID(tableName, property)))
+		if aliasTableName == "" {
+			aliasTableName = tableName
+		}
+		cols = append(cols, makeColumn(aliasTableName, property)+" as "+quote(makeColumnID(tableName, property)))
```
Comment (nati) [inline db/sql/sql.go]: I don't understand this part.  

quote(makeColumnID(tableName, property)

I guess there would be case in that some properties get shadowed, right?
quote(makeColumnID(aliasTableName, property) works?

In this case, we can omit aliasTableName too

File: server/server_test.go [hunk 5]
```diff
@@ -237,6 +241,38 @@ var _ = Describe("Server package test", func() {
...
+
+			By("creating 1 parent")
+			charlieParent := getParent("charlie", bobChild["id"].(string), aliceChild["id"].(string))
+			testURL("POST", parentsPluralURL, adminTokenID, charlieParent, http.StatusCreated)
+
+			By("assuring 1 parent was returned without error")
+			result := testURL("GET", parentsPluralURL, adminTokenID, nil, http.StatusOK)
+			res := result.(map[string]interface{})
+			parents := res["parents"].([]interface{})
+			Expect(parents).To(HaveLen(1))
```
Comment (nati) [inline server/server_test.go]: Could you check this response contains related resources?

**Comment by morrisson** [comment]
I need to fix decode part additionally, but it should be simpler. Thanks for your comments.

File: server/server_test.go [hunk 6]
```diff
@@ -1161,12 +1246,22 @@ func clearTable(tx transaction.Transaction, s *schema.Schema) error {
 	if s.IsAbstract() {
 		return nil
 	}
+	fmt.Println(schema.GetManager().Schemas())
```
Comment (nati) [inline server/server_test.go]: debug?

**Comment by nati** [comment]
Thanks! the patch get really clean.
could you also run make in your local env before push? I guess lint tool such as go fmt isn't applied 
for this code.

File: server/server_test.go (hunk 6 above)
Comment (morrisson) [inline server/server_test.go]: Oops. Sorry.

**Comment by nati** [comment]
Thanks LGTM
